name: A workflow for my Reporting System
on: push

jobs:
  build:
    name: Reporting System action
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Package with Maven
        run: mvn --batch-mode clean package
      - name: Build Docker Image
        run: docker build -t coursework-app .
      - name: Start MongoDB
        run: docker run -d --name mongodb -p 27000:27017 mongo:4.4
      - name: Wait for MongoDB
        run: sleep 15
      - name: Run application
        run: docker run --network host --rm coursework-app
    

